import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

const stardust = localFont({
  src: [
    { path: "./font/PF스타더스트.ttf", weight: "400", style: "normal" },
    { path: "./font/PF스타더스트 Bold.ttf", weight: "700", style: "bold" },
  ],
  display: "swap",
  variable: "--PFstardust",
});

export const metadata: Metadata = {
  title: "toVillage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className="scrollbar-hide">
      <body>
        <div className="container relative h-screen min-h-screen mx-auto bg-white max-w-7xl ">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
