import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Weekly from "@/components/WeeklyCalendar/Weekly";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "toVillage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scrollbar-hide">
      <body className={inter.className}>
        <div className="container mx-auto relative flex min-h-screen flex-col items-center max-w-7xl bg-white ">
          <Weekly />
          {children}
        </div>
      </body>
    </html>
  );
}
